
POST http://localhost/hometext_Api/public/api/my-profile-update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2hvbWV0ZXh0X0FwaS9wdWJsaWMvYXBpL3VzZXItcmVnaXN0cmF0aW9uIiwiaWF0IjoxNjg0NDMyMjkxLCJleHAiOjE2ODQ0MzU4OTEsIm5iZiI6MTY4NDQzMjI5MSwianRpIjoibFdEWkN3dHROVktqbmpxYiIsInN1YiI6IjQwIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.nE-XHgkQ5vNp6-OVqL2dhN0XdLczvqH1bp7z348SYE0


